# Generated by Django 5.0.1 on 2024-02-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='image_file',
            field=models.ImageField(null=True, upload_to='spectogram_uploads/'),
        ),
    ]
